name: Prepare Ubuntu image

on:
  workflow_call:

jobs:
  prepare_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - uses: browser-actions/setup-geckodriver@latest
      - run: geckodriver --version
      - run: which geckodriver
