name: PR builder (sanity check, no deploy)

on:
  pull_request:
    branches:
      - website-v2

jobs:
  website-pr:
    name: Build the Rascal website
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - uses: browser-actions/setup-geckodriver@latest
      - run: geckodriver --version
      - run: which geckodriver

      - name: Copy from Maven dependencies
        run: echo mvn dependency:unpack

      - name: Run docs through shell
        run: echo mvn rascal:tutor -Dwebdriver.gecko.driver=geckodriver
      - name: Copy assets
        run: echo mvn rascal:tutor-assets

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build