name: Test deployment

on:
  pull_request:
    branches:
      - website-v2
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  website-pr:
    name: Build the Rascal website
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Setup toolchain
        uses: ./.github/workflows/_setup.yml

      - name: Build website
        uses: ./.github/workflows/_build.yml