name: PR builder (sanity check, no deploy)

on:
  pull_request:
    branches:
      - website-v2

jobs:
  website-pr:
    name: Build the Rascal website
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Clone
        uses: actions/checkout@v3

        # Do the base actions
      - uses: ./.github/base-jobs.yml

      # Do a dummy build to see if there are errors
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
