name: PR builder (sanity check, no deploy)

on:
  pull_request:
    branches:
      - website-v2

jobs:
  website-pr:
    name: Build the Rascal website
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 1047731
      - run: which chrome
      - uses: nanasess/setup-chromedriver@v1
      - run: which chromedriver

      # Copy docs from dependent projects, run tutor on local courses folder and copy results into docs and static/assets
      - name: Run rascal-tutor and reuse libraries
        run: mvn clean package -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver -Dwebdriver.chrome.browser=`which chrome`

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
