name: PR builder (sanity check, no deploy)

on:
  pull_request:
    branches:
      - website-v2

jobs:
  prepare-website:
    uses: ./.github/workflows/base-jobs.yml

  website-pr:
    name: Sanity check the Rascal website
    runs-on: buildjet-4vcpu-ubuntu-2204
    needs: prepare-website
    steps:
      # Download prepared sources from base
      - name: Download sources
        uses: actions/download-artifact@v4
        with:
          name: sources

      # Do a dummy build to see if there are errors
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
