name: Deploy to GitHub Pages

on:
  push:
    branches:
      - website-v2
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  website:
    name: Build the Rascal website
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - uses: browser-actions/setup-geckodriver@latest
      - run: geckodriver --version
      - run: which geckodriver

      - name: Copy from Maven dependencies
        run: echo mvn dependency:unpack

      - name: Run docs through shell
        run: echo mvn rascal:tutor -Dwebdriver.gecko.driver=geckodriver
      - name: Copy assets
        run: echo mvn rascal:tutor-assets

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v1.8.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_KEY }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
