name: Deploy to Netlify

on:
  push:
    branches:
      - website-v2
   
jobs:
  website:
    name: Build the Rascal website
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - uses: browser-actions/setup-firefox@latest
      - run: firefox --version
      - uses: browser-actions/setup-geckodriver@latest
      - run: geckodriver --version      

      - name: Run Maven Rascal Tutor plugin
        run: mvn clean package

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v1.8.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_KEY }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
