name: Deploy to Netlify

on:
  push:
    branches:
      - website-v2
   
jobs:
  prepare-website:
    uses: ./.github/workflows/base-jobs.yml

  website:
    name: Deploy the Rascal website
    runs-on: buildjet-4vcpu-ubuntu-2204
    needs: prepare-website
    steps:
      # Download prepared sources from base
      - name: Download sources
        uses: actions/download-artifact@v3
        with:
          name: sources

      # Production deploy
      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_KEY }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: yarn install --frozen-lockfile
          build_command: yarn build

      # Production reindex    
      - name: Algolia crawler creation and crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.10
        id: algolia_crawler
        with:
          crawler-api-base-url: 'https://crawler.algolia.com/api/1/'
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://www.rascal-mpl.org'
          crawler-name: 'rascal'
